// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulpqgizcyvmeuyryzvas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscHFnaXpjeXZtZXV5cnl6dmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjE3MDgsImV4cCI6MjA3NDM5NzcwOH0.GUtw-LNWj5ucTgdY9z3KkGxTCiszZYQBRq9cgs_62_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});